<?php

return [
    [
        'slug' => 'i_am_an_idiot',
        'points' => 500, 
        'title' => 'I am an idiot',
        'secret' => true,
        'description' => "Avoir mal renseigné ses réseaux sociaux, faut pas mettre le http espèce de con !",
    ],
    [
        'slug' => 'valerie_damidot',
        'points' => 500, 
        'title' => 'Valerie Damidot',
        'secret' => true,
        'description' => "Avoir modifié 5 fois sa banniere, mais oui t'es belle.",
    ],
    [
        'slug' => 'i_love_this_game',
        'points' => 500, 
        'title' => "J'adore ce jeu",
        'secret' => true,
        'description' => 'Avoir plus de 10 clips sur le même jeu.',
    ],
    [
        'slug' => 'unloved',
        'points' => 1, 
        'title' => 'Le Mal-aimé',
        'secret' => true,
        'description' => 'Avoir plus de 20 clips refusés... tu vas commencer à nous casser les couilles toi.',
    ],
    [
        'slug' => 'pharos',
        'points' => 750, 
        'title' => 'PHAROS',
        'description' => "Avoir renseigné une banniere, sa description et l'un de ses réseaux. Bravo, on peut désormais venir te choper",
    ],
    [
        'slug' => 'famous',
        'points' => 1000, 
        'title' => 'Famous',
        'description' => 'Avoir un clip avec plus de 500 vues.',
    ],
    [
        'slug' => 'compulsive_clipper',
        'points' => 500, 
        'title' => 'Clipper compulsif',
        'description' => 'Avoir réalisé plus de 7 clips en une semaine.',
    ],
    [
        'slug' => 'architect',
        'points' => 500, 
        'title' => 'Architecte',
        'description' => "Avoir contribué au développement du site.",
    ],
    [
        'slug' => 'beta_test',
        'points' => 500, 
        'title' => 'Bêta-testeur',
        'description' => "Avoir contribué à la bêta-test du site ❤️",
    ],
    [
        'slug' => 'ten_active_clips',
        'points' => 500, 
        'title' => 'Ten active clips',
        'description' => 'Avoir 10 clips.',
        'always' => false,
    ],
    [
        'slug' => 'thirty_active_clips',
        'points' => 500, 
        'title' => 'Thirty active clips',
        'description' => 'Avoir 30 clips.',
        'always' => false,
    ],
    [
        'slug' => 'fifty_active_clips',
        'points' => 500, 
        'title' => 'Fifty active clips',
        'description' => 'Avoir 50 clips.',
        'always' => false,
    ],
    [
        'slug' => 'seventy_active_clips',
        'points' => 500, 
        'title' => 'Seventy active clips',
        'description' => 'Avoir 70 clips',
        'always' => false,
    ],
    [
        'slug' => 'hundred_active_clips',
        'points' => 750, 
        'title' => 'Hundred active clips',
        'description' => 'Avoir 100 clips.',
        'always' => false,
    ],
    [
        'slug' => 'one_hundred_fifty_active_clips',
        'points' => 750, 
        'title' => 'One Hundred Fifty active clips',
        'description' => 'Avoir 150 clips.',
        'always' => false,
    ],
    [
        'slug' => 'thousand_views_all_clips',
        'points' => 500, 
        'title' => "1'000 vues !",
        'description' => "Avoir accumulé 1'000 vues. sur ses clips.",
    ],
    [
        'slug' => 'two_thousand_views_all_clips',
        'points' => 500, 
        'title' => "2'000 vues !",
        'description' => "Avoir accumulé 2'000 vues. sur ses clips.",
    ],
    [
        'slug' => 'three_thousand_views_all_clips',
        'points' => 500, 
        'title' => "3'000 vues !",
        'description' => "Avoir accumulé 3'000 vues sur ses clips.",
    ],
];
