<?php

return [
    [
        'slug' => 'pharos',
        'points' => 500, 
        'title' => 'PHAROS',
        'secret' => true,
        'description' => "Avoir renseigné une banniere, sa description et l'un de ses réseaux. Bravo, on peut désormais venir te choper",
    ],
    [
        'slug' => 'valerie_damidot',
        'points' => 500, 
        'title' => 'Valerie Damidot',
        'secret' => true,
        'description' => null,
    ],
    [
        'slug' => 'famous',
        'points' => 500, 
        'title' => 'Famous',
        'secret' => true,
        'description' => 'Avoir un clip avec plus de 500 vues.',
    ],
    [
        'slug' => 'compulsive_clipper',
        'points' => 500, 
        'title' => 'Compulsive clipper',
        'secret' => true,
        'description' => null,
    ],
    [
        'slug' => 'i_love_this_game',
        'points' => 500, 
        'title' => 'I love this game',
        'secret' => true,
        'description' => null,
    ],
    [
        'slug' => 'unloved',
        'points' => 500, 
        'title' => 'Unloved',
        'secret' => true,
        'description' => null,
    ],
    [
        'slug' => 'ten_active_clips',
        'points' => 500, 
        'title' => 'Ten active clips',
        'description' => null,
    ],
    [
        'slug' => 'thirty_active_clips',
        'points' => 500, 
        'title' => 'Thirty active clips',
        'description' => null,
    ],
    [
        'slug' => 'fifty_active_clips',
        'points' => 500, 
        'title' => 'Fifty active clips',
        'description' => null,
    ],
    [
        'slug' => 'seventy_active_clips',
        'points' => 500, 
        'title' => 'Seventy active clips',
        'description' => null,
    ],
    [
        'slug' => 'hundred_active_clips',
        'points' => 500, 
        'title' => 'Hundred active clips',
        'description' => null,
    ],
    [
        'slug' => 'one_hundred_fifty_active_clips',
        'points' => 500, 
        'title' => 'One Hundred Fifty active clips',
        'description' => null,
    ],
    [
        'slug' => 'thousand_views_all_clips',
        'points' => 500, 
        'title' => 'Thousand views all clips',
        'description' => null,
    ],
    [
        'slug' => 'two_thousand_views_all_clips',
        'points' => 500, 
        'title' => 'Two thousand views all clips',
        'description' => null,
    ],
    [
        'slug' => 'three_thousand_views_all_clips',
        'points' => 500, 
        'title' => 'Three thousand views all clips',
        'description' => null,
    ],
];
